### ISSUE TITLE
Branching, Git Branch Organization.

### ISSUE THREAD

**Issue by DiaboloAB** [GriffonAV/GriffonAV#1]

**Comment by ewen1507** [comment]
# Deployment Guide - Griffon

## Repository Setup

Le projet Griffon est structuré selon une stratégie de branches permettant un développement collaboratif clair et sécurisé.

---

## CI/CD Pipeline

Nous utilisons **GitHub Actions** comme solution d’intégration et de déploiement continu. La configuration est stockée dans `.github/workflows/ci.yml`.

### Objectifs de la CI/CD

- Automatiser le build de l’application (CLI en Rust et GUI en Tauri/React).
- Lancer automatiquement les tests unitaires et d’intégration.
- Assurer la qualité du code via des outils de linting et de formatage.
- Vérifier la sécurité des dépendances.
- Construire une image Docker à jour à chaque mise à jour sur `develop` ou `main`.

---

## Étapes de la pipeline CI

### 1. **Build Rust**
- Compilation avec `cargo build --release`
- Vérification de la syntaxe via `cargo check`
- Vérification des Dependences (voir [Verifying Latest Dependencies](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-latest-dependencies))

```
jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --verbose
```
- Vérification de la version Rust si indiqué (voir [Verifying rust-version](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version))
```
jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - run: cargo hack check --rust-version --workspace --all-targets --ignore-private

```

### 2. **Tests Backend (Rust)**
- `cargo test` pour les tests unitaires et d’intégration (voir [Unit testing](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#unit-testing))
- `cargo clippy` pour les bonnes pratiques Rust (voir [Usage](https://doc.rust-lang.org/clippy/usage.html#usage))
- `cargo fmt` pour le formatage
- `cargo audit` pour l’audit de sécurité des dépendances (voir [Doc Audit](https://crates.io/crates/cargo-audit))

### 3. **Build Frontend (React + Tauri)**
- Installation des dépendances avec `pnpm install`
- Lint JS avec `eslint`
- Tests unitaires avec `vitest`
- Build final avec `pnpm build` et `cargo tauri build`

### 4. **Docker**
- Construction d’une image Docker à chaque `push` sur `prod` ou `pre-prod`
- L'image est utilisée pour les tests d’intégration et peut être poussée vers un registre DockerHub ou GHCR (à configurer).

---
